### ISSUE TITLE
Upload does not work on firefox

### ISSUE THREAD

**Issue by Ablu** [stfnhmplr/pagekit-gallery#19] opened 2017-02-14 10:55 UTC
Hi,

if I upload pictures on firefox the progress counter on the browser console finishes but nothing happens. On chrome it works as expected.

**Comment by stfnhmplr** [comment] 2017-02-23 20:42
hi, i can't reproduce that. is there any error message on the console? works for me with firefox 51.0.1@macos

**Comment by stfnhmplr** [comment] 2017-06-08 07:26
Hey there!

I close this issue since the original poster (or another commenter) hasn't yet responded to the question or request made to them 14 days ago. If the issue still exists, let me know with a comment and i will reopen it.

Thanks!

**Closed by stfnhmplr** 2017-06-08 07:26 UTC

**Comment by Ablu** [comment] 2017-10-23 14:47
I was also unable to reproduce it
