### ISSUE TITLE
Upload gives no feedback except on browser console

### ISSUE THREAD

**Issue by Ablu** [stfnhmplr/pagekit-gallery#18] opened 2017-02-14 10:40 UTC
Hi,

if I select multiple files to upload (either by file picker or by drag an drop) and press upload the uploader immediately displays 100 and a full progress bar. On the browser console I can then see some debug prints for the upload:
![screenshot from 2017-02-14 11-36-46](https://cloud.githubusercontent.com/assets/741061/22925711/0eec30a4-f2aa-11e6-905d-db44016d7eee.png)

This is very irritating for a non technical user. It does not appear like anything is happening on the page at all if you do not open the console.

The behaviour is the same under Firefox and Chrome.

**Comment by Ablu** [comment] 2017-02-14 10:43
The issue seems to be this `ceil` call here: `_this.$set('progress', Math.ceil(e.loaded / e.total) * 100);`

I think the `* 100` should go into the parenthesis?

**Comment by stfnhmplr** [comment] 2017-02-23 20:32
thanks for your report. this will be fixed with the next release.

**Comment by nicolas-pecher** [comment] 2017-04-05 12:41
First I want to say thanks for this great extension. It's working really well except this faulty progress bar. I'm using your extension on serveral sites and my customers are quite confused by this bug. When can we expect the next release?

**Comment by stfnhmplr** [comment] 2017-04-07 06:24
I'll publish the next release this weekend.

**Comment by nicolas-pecher** [comment] 2017-04-11 15:04
The issue is solved with the latest release. Thanks for the update!

**Comment by stfnhmplr** [comment] 2017-04-12 07:23
You're welcome.

**Closed** 2017-04-12 07:24 UTC
